---
title: TechLab
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@techlab.lv
description: "TechLab - community for technology entrepreneurs, scientists, coders
  and engineers.. a place where new startups are born. \n"
baseurl: 
url: http://www.techlab.lv
facebook_address: https://www.facebook.com/techlablatvia/
markdown: kramdown
exclude:
- CNAME
- LICENSE
- README.md
- run.sh
